config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :episodes, :except => [:index] do 
    member do
      put "watch", to: "episodes#watch"
    end
  end
  resources :series, :only => [:index, :show] do
    collection do
      post "add", to: "series#add"
      post "addnouser", to: "series#addnouser"
      post "adduser", to: "series#adduser"
    end
  end
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/", to: redirect(path: "/to-watch")
  get "to-watch", to: "series#index"
  # get "users/:id/profile", to: "profile#show"
  resources :comments
  resources :profile do
    member do
      get "recent", to: "profile#recent"
    end
  end
end

app/models/episode.rb
class Episode < ApplicationRecord
    belongs_to :season
    has_and_belongs_to_many :users
    has_many :comments, dependent: :destroy
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_episode, only: [:show, :watch]

  # GET /episodes/1
  # GET /episodes/1.json
  def show
    @comment = @episode.comments.build
    @comments = @episode.comments.all.order(created_at: :desc)
  end

  def watch
    return current_user.episodes.delete(@episode) if current_user.episodes.include?(@episode)
    show = Series.find(@episode.season.series_id)
    unless current_user.series.include?(show)
      p "user hasn't added the show to their list yet"
      current_user.series << show
    end
    p "marking episode as watched"
    current_user.episodes << @episode 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_episode
      @episode = Episode.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def episode_params
      params.fetch(:episode, {})
    end
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/views/episodes/_form.html.erb
<%= form_with(model: episode, local: true) do |form| %>
  <% if episode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(episode.errors.count, "error") %> prohibited this episode from being saved:</h2>

      <ul>
        <% episode.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/episodes/edit.html.erb
<h1>Editing Episode</h1>

<%= render 'form', episode: @episode %>

<%= link_to 'Show', @episode %> |
<%= link_to 'Back', episodes_path %>

app/views/episodes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Episodes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @episodes.each do |episode| %>
      <tr>
        <td><%= link_to 'Show', episode %></td>
        <td><%= link_to 'Edit', edit_episode_path(episode) %></td>
        <td><%= link_to 'Destroy', episode, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Episode', new_episode_path %>

app/views/episodes/new.html.erb
<h1>New Episode</h1>

<%= render 'form', episode: @episode %>

<%= link_to 'Back', episodes_path %>

app/views/episodes/show.html.erb
<% content_for :title, @episode.title %>
<div class="episode-wrapper">
    <div class="header">
        <div class="episode-banner">
            <div class="episode-info">
                <h2><%= @episode.title %></h2>
                <%= link_to watch_episode_path(@episode), method: :put, id: "added-btn-js", class: getWatchedClass(@episode) do %>
                    <span id="added-js"><%= getWatchedText(@episode) %></span>
                <% end %>
            </div>
            <div class="dark-overlay"></div>
        </div>
    </div>
    <div class="show-meta">
        <%= whipUpEpisodeMeta(@episode) %>
    </div>
    <div class="episode-container">
    <h2>Episode discussions:</h2>
    <%= render partial: 'comments/form', locals: { comment: @comment, episode: @episode } if user_signed_in? %>
    <% @comments.each do |comment| %>
        <div class="comment" id="comment-js">
            <div class="comment-inner">
                <div>
                    <span><%= comment.user.username %></span>
                    <span class="comment-time"><%= time_ago_in_words(comment.created_at) %> ago</span>
                    <%= link_to 'Delete', comment_path(comment), method: :delete, id: 'comment-delete-js' if user_signed_in? && comment.user == current_user %>
                </div>
                <p><%= comment.body %></p>
            </div>
        </div>
    <% end %>
    </div>
</div>

<script>
    const addBtnE = $('#added-btn-js');
    const addTextE = $('#added-js');

    const delcom = $('*#comment-delete-js');

    addBtnE.click(() => {
        if (addBtnE.hasClass("watched"))
            addTextE.text("WATCHED?");
        else
            addTextE.text("WATCHED!");
        addBtnE.toggleClass("watched");
    })

    delcom.each(function() {
        $(this).on('click', function(e) {
            $(this).parent().parent().parent().remove()
        })
    })
</script>