config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :episodes, :except => [:index] do 
    member do
      put "watch", to: "episodes#watch"
    end
  end
  resources :series, :only => [:index, :show] do
    collection do
      post "add", to: "series#add"
      post "addnouser", to: "series#addnouser"
      post "adduser", to: "series#adduser"
    end
  end
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/", to: redirect(path: "/to-watch")
  get "to-watch", to: "series#index"
  # get "users/:id/profile", to: "profile#show"
  resources :comments
  resources :profile do
    member do
      get "recent", to: "profile#recent"
    end
  end
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_series, only: [:show]

  def index
    if params[:q] && !params[:q].empty?
      response = Excon.get("https://api.thetvdb.com/search/series?name=#{params[:q]}", :headers => { "Authorization" => "Bearer #{Series.fetch_token}" })
      if response.status != 200
        results = nil
      else
        results = JSON.parse(response.body)["data"]
      end
    else
      results = Series.joins(:users).where("users.id" => current_user.id).select("series.*, series.tvdb_id as id")
    end
    @series = Array.new
    results.each do |show|
      stored = Series.where(tvdb_id: show["id"])
      p stored
      if stored.present?
        @series << {
          :tvdb_id => stored[0].tvdb_id,
          :title => stored[0].title.to_s,
          :summary => stored[0].summary,
          :image => stored[0].image,
          :first_aired => stored[0].first_aired,
          :status => stored[0].status,
          :stored => true
        }
      else
        @series << {
          :tvdb_id => show["id"],
          :title => show["seriesName"],
          :summary => show["overview"],
          :image => show["image"],
          :first_aired => show["firstAired"],
          :status => show["status"],
        }
      end
    end
  end

  def show
    FetchEpisodesJob.perform_later(@series.tvdb_id, true)
    @test = Array.new
    @test << {
      :tvdb_id => @series.tvdb_id,
      :title => @series.title.to_s,
      :summary => @series.summary,
      :image => @series.image,
      :first_aired => @series.first_aired,
      :status => @series.status,
      :stored => true      
    }
  end

  def add
    stored = Series.where(tvdb_id: params["tvdb_id"])
    if stored.present?
      FetchEpisodesJob.perform_later(params["tvdb_id"], true)
      if current_user.series.where(tvdb_id: params["tvdb_id"]).present?
        # should i do something here?
      else
        current_user.series << stored
      end
    else
      FetchEpisodesJob.perform_later(params["tvdb_id"], false)
      series = Series.new
      series.tvdb_id = params["tvdb_id"]
      series.title = params["title"]
      series.summary = params["summary"]
      series.image = params["image"]
      series.first_aired = DateTime.parse(params["first_aired"])
      series.status = params["status"]
      series.save
      current_user.series << series
      current_user.save
    end
  end
  def addnouser
    FetchEpisodesJob.perform_later(params["tvdb_id"], true)
    series = Series.where(tvdb_id: params["tvdb_id"])
    if series.length > 0
      return redirect_to series[0]
    end 

    series = Series.new
    series.tvdb_id = params["tvdb_id"]
    series.title = params["title"]
    series.summary = params["summary"]
    series.image = params["image"]
    series.first_aired = DateTime.parse(params["first_aired"])
    series.status = params["status"]
    series.save
    redirect_to series
  end

  def adduser
    show = Series.where(tvdb_id: params["tvdb_id"])
    return current_user.series.delete(show[0]) if current_user.series.include?(show[0])
    current_user.series << show
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_series
    @series = Series.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def series_params
    params.fetch(:series, :q, :test, {})
  end
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/series/index.html.erb
<% if params[:q] %>
<h2 class="search-results">TV Shows matching "<%= params[:q] %>"</h2>
<% end %>
<div class="card-wrapper">
<% if @series.blank? %>
<div class="no-seasons">
    <h2>There doesn't seem to be anything here</h2>
    <i class="uil uil-sad-squint"></i>
    <h3>Use the search to look for shows you watch.</h3>
</div>
<% end %>
<% @series.each do |show| %>
    <div class="card-serie">
        <% 
            if show[:stored] 
                url = adduser_series_index_path(show) 
            else
                url = add_series_index_path(show)
            end
        %>
        <%= link_to url, id: "added-btn-js", class: getAddedClass(show[:tvdb_id]), method: :post do %>
            <i class="uil uil-check"></i>
        <% end %>
        <%= link_to addnouser_series_index_path(show), method: :post do %>
            <%= image_tag urlmagic('https://proxy.plazovnik.si?url=https://thetvdb.com', show[:image]), :alt => show[:title]%>
            <p><%= show[:title] %></p>
        <% end %>
    </div>
<% end %>
</div>

<script>
    const addBtn = $('*#added-btn-js');

    addBtn.each(function() {
        $(this).on('click', function(e) {
            $(this).toggleClass("added")
        })
    })

</script>

app/views/series/show.html.erb
<% content_for :title, @series.title %>
<div class="series-wrapper">
    <div class="header">
        <div class="series-banner" style="background-image: url('<%= urlmagic("https://proxy.plazovnik.si?url=https://thetvdb.com", @series.image)%>');">
            <div class="series-info">
                <h2><%= @series.title %></h2>
                <%= link_to (adduser_series_index_path(@test).sub! '.', '?'), id: "added-btn-js", class: getAddedClass(@series.tvdb_id), method: :post do %>
                    <span id="added-js"><%= getAddedText(@series.tvdb_id) %></span>
                <% end %>
            </div>
            <div class="dark-overlay"></div>
        </div>
    </div>
    <div class="show-meta">
        <% if @series.status == "Continuing"%>
            <span><%= @series.airs_day_of_week %> at <%= @series.airs_time %></span> &middot;
        <% end %>
        <span><%= @series.seasons.all.count %></span> &middot;
        <span><%= @series.status %></span>
        <p><%= @series.summary %></p>
    </div>
    <div class="series-container">
    <% if @series.seasons.blank? %>
        <div class="no-seasons">
            <h2>There doesn't seem to be anything here</h2>
            <i class="uil uil-sad-squint"></i>
            <h3>Check again in a few minutes!</h3>
        </div>
    <% end %>
    <% @series.seasons.order("number asc").each do |season| %>
        <div class="season">Season <%= season.number%></div>
        <table>
            <tr>
                <td>Episode</td>
                <td>Title</td>
                <td>Aired</td>
            </tr>
        <% season.episodes.order("date_aired, title asc").each_with_index do |episode, index| %>
            <%= link_to episode_path(episode) do %>
                <tr>
                    <td><%= index + 1 %></td> 
                    <td><%= link_to episode.title, episode_path(episode) %></td>
                    <td><%= episode.date_aired.to_date if episode.date_aired %></td>
                </tr>
            <% end %>
        <% end %>
        </table>
    <% end %>
    </div>
</div>

<script>
    const addBtn = $('#added-btn-js');
    const addText = $('#added-js');

    addBtn.click(() => {
        if (addBtn.hasClass("added"))
            addText.text("Add");
        else
            addText.text("Remove");
        addBtn.toggleClass("added");
    })
</script>