config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :episodes, :except => [:index] do 
    member do
      put "watch", to: "episodes#watch"
    end
  end
  resources :series, :only => [:index, :show] do
    collection do
      post "add", to: "series#add"
      post "addnouser", to: "series#addnouser"
      post "adduser", to: "series#adduser"
    end
  end
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/", to: redirect(path: "/to-watch")
  get "to-watch", to: "series#index"
  # get "users/:id/profile", to: "profile#show"
  resources :comments
  resources :profile do
    member do
      get "recent", to: "profile#recent"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= (yield(:title) + " - " unless yield(:title).blank?).to_s + "tvtracker" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" src="https://use.fontawesome.com/releases/v5.0.13/css/all.css">
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v2.1.6/css/unicons.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.min.js"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ezfix2">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <div class="page-wrapper chiller-theme toggled">
      <a id="show-sidebar" class="btn btn-sm btn-dark" href="#">
        <i class="fas fa-bars"></i>
      </a>
      <nav id="sidebar" class="sidebar-wrapper">
        <div class="sidebar-content">
          <div class="sidebar-brand">
            <%= link_to "TV TRACKER", to_watch_path %>
          </div>
          <% if user_signed_in? %>
          <div class="sidebar-header">
            <div class="user-pic">
              <!--<img class="img-responsive img-rounded" src="https://raw.githubusercontent.com/azouaoui-med/pro-sidebar-template/gh-pages/src/img/user.jpg"
                alt="User picture">-->
                <h2 style="height: 40px; width: 40px; color: #121212; background-color: lightblue; border-radius: 10px; display: inline-flex; justify-content: center; align-items: center"><%= profileInitials %></h2>
            </div>
            <div class="user-info">
              <span class="user-name">
                <%= current_user.first_name %>
                <%= current_user.last_name %>
              </span>
              <span style="font-size: .85em; color: #aaa; line-height: 1.5em">
                Member for <%= time_ago_in_words(current_user.created_at) %>
              </span>
            </div>
          </div>
          <% end %>
          <% if user_signed_in? %>
          <div class="sidebar-search">
          <%= form_tag series_index_url, :method => 'get' do %>
            <div class="input-group">
              <%= text_field_tag :q, params[:q], placeholder: 'Search...', :class => ["form-control", "search-menu"] %>
              <%= button_tag :submit do %>
                  <div class="input-group-append">
                    <span class="input-group-text">
                      <i class="fa fa-search" aria-hidden="true"></i>
                    </span>
                  </div>
              <% end %>
            </div>
          <% end %>              
          </div>
          <% end %>
          <div class="sidebar-menu">
            <ul>
              <% if user_signed_in? %>
              <li>
                <%= link_to profile_path(current_user) do %>
                  <span>Profile</span>
                <% end %>
              </li>
              <li>
                <%= link_to recent_profile_path(current_user) do %>
                  <span>Recent activity</span>
                <% end %>
              </li>
              <li>
                <%= link_to edit_user_registration_path do %>
                  <span>Edit profile</span>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <span>Logout</span>
                <% end %>
              </li>
              <% else %>
                <li>
                <%= link_to new_user_session_path do %>
                  <span>Login</span>
                <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
        <!--<div class="sidebar-footer">
        </div>-->
      </nav>
      <main class="page-content">
        <div class="container-fluid">
        <%= yield %>
        </div>
      </main>
    </div>
  </body>
</html>

<style>
.ezfix2 {
  position: fixed;
  right: 10px;
  bottom: 20px;
  border-radius: 5px;
  z-index: 999;
  padding: 10px;
}
</style>